version: '3.7'

services:
  woocommerce: &woocommerce
    build: &build
      context: .
      args:
        version: "6.1.1"
        wc_version: "7.1.1"
    ports:
      - 80:80
    depends_on:
      - mysql
    volumes:
      - /var/www/html
      - ./wc-begateway-payment:/var/www/html/wp-content/plugins/wc-begateway-payment
      - ./docker/src/languages:/var/www/html/wp-content/languages
    networks:
      - default
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_HOST: mysql:3306

  mysql:
    image: mysql:5.6
    networks:
      - default
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
